version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - "./tmp/shared/temp/zookeeper:/opt/zookeeper-3.4.6/data"
  kafka:
    image: wurstmeister/kafka:0.10.0.1
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    links:
      - zookeeper
    volumes:
      - "./tmp/shared/temp/kafka:/kafka"
  redis:
    image: 'redis:3.2.4'
    ports:
      - "6379:6379"
